In [62]:
import numpy as np
import struct
import os
import pickle
trainsamples = 50000
perc = 0.001
label_bytes = 1  # 2 for CIFAR-100
image_bytes = 32 * 32 * 3
data_dir = "//code/logs/cifar10_data/cifar-10-batches-bin/"
  # Every record consists of a label followed by the image, with a
  # fixed number of bytes for each.
record_bytes = label_bytes + image_bytes

filenames = [os.path.join(data_dir, 'data_batch_%d' % i)
                 for i in xrange(1, 6)]
#filenames = [os.path.join(data_dir, 'test_batch')]

In [63]:
keeplab = np.concatenate([np.ones((trainsamples*perc),dtype='int32'),np.zeros((trainsamples-trainsamples*perc),dtype='int32')],0)
np.random.shuffle(keeplab)

/opt/conda/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


In [64]:
with open('//code/logs/cifar10labels.pkl','rb') as f:
    labels = pickle.load(f)

In [65]:
print(keeplab)
if 1: #balance check
    print(np.unique(labels[keeplab==1],return_counts=True))

[0 0 0 ..., 0 0 0]
(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), array([ 3,  6,  3,  5,  4,  4,  4, 11,  4,  6]))


In [66]:
with open('//code/logs/superclass_tsne_pool5.pkl','rb') as f:
    superclasslab = pickle.load(f)

In [67]:
keeplab[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [68]:
superclasslab[:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [69]:
print(len(keeplab))
print(len(superclasslab))

50000
50000


In [70]:
if 0:
    i=0
    for fname in filenames:
        with open(fname+'.bin', 'rb') as old_buffer, open(fname+'_1perc.bin', 'wb') as new_buffer:
            part = old_buffer.read(record_bytes)
            while part:
                # insert new content
                #new_buffer.write(chr(superclasslab[i]))
                new_buffer.write(chr(keeplab[i]))
                # copy until nth byte
                new_buffer.write(part)
                part = old_buffer.read(record_bytes)
                i+=1
        print('did a file!')

In [71]:
if 1:
    i=0
    with open('//code/logs/cifar10_data/cifar-10-batches-bin/data_batch_01perc_skip.bin', 'wb') as new_buffer:
        for fname in filenames:
            with open(fname+'.bin', 'rb') as old_buffer:
                part = old_buffer.read(record_bytes)
                while part:
                    # insert new content
                    if keeplab[i]==1:
                        # copy until nth byte
                        new_buffer.write(chr(keeplab[i]))
                        new_buffer.write(part)
                    part = old_buffer.read(record_bytes)
                    i+=1

In [72]:
os.stat(filenames[4]+'.bin')

posix.stat_result(st_mode=33188, st_ino=30671002, st_dev=2065, st_nlink=1, st_uid=2156, st_gid=1103, st_size=30730000, st_atime=1500464519, st_mtime=1244144138, st_ctime=1498639486)

In [17]:
os.stat(filenames[4]+'_0perc_tsned7.bin')

posix.stat_result(st_mode=33188, st_ino=30671771, st_dev=2065, st_nlink=1, st_uid=0, st_gid=0, st_size=30750000, st_atime=1499431464, st_mtime=1499445512, st_ctime=1499445512)

In [18]:
os.stat('//code/logs/cifar10_data/cifar-10-batches-bin/data_batch_1perc_skip.bin')

posix.stat_result(st_mode=33188, st_ino=30671853, st_dev=2065, st_nlink=1, st_uid=0, st_gid=0, st_size=153700000, st_atime=1500284705, st_mtime=1500464519, st_ctime=1500464519)

In [19]:
1536500/record_bytes

500

In [20]:
i

50000