In [ ]:
import os

In [ ]:
os.system("python cifar10_train_VGG16.py")

In [ ]:
print('finished!')

In [ ]:
if 1:
    import pickle
    with open('//code/logs/cifarVGGtrainfeats.pkl','rb') as f:
        feats = pickle.load(f)

In [ ]:
feats = feats[:1000]

In [ ]:
#import os
#os.environ["CUDA_VISIBLE_DEVICES"]=""
import VGG16base
import tensorflow as tf
import cifar10_input_VGG16 as cifarin
import matplotlib.pyplot as plt
import numpy as np
import scipy

import sys
sys.path.insert(0, '//code/bhtsne')
import bhtsne

def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo)
    return dict

In [ ]:
embedding_array = bhtsne.run_bh_tsne(feats, initial_dims=feats.shape[1])

In [ ]:
import numpy as np
import pickle

In [ ]:
perc = 0.1
setsize = 50000
randperc = np.random.shuffle(np.hstack([np.ones(setsize*perc),np.zeros(setsize-setsize*perc)]))

In [ ]:
randperc

In [ ]:
t=[]


In [ ]:
t.append(1)

In [ ]:
t

In [1]:
import cifar10_input_VGG16_PL as inputPL
import tensorflow as tf

In [2]:
img,lbl,suplbl = inputPL.distorted_inputs('//code/logs/cifar10_data/cifar-10-batches-bin', 48,partially_labelled=True)

Tensor("Cast:0", dtype=int32)
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Tensor("shuffle_batch:1", shape=(48, 2, 6), dtype=float32)


In [3]:
sess = tf.Session()
with sess.as_default():
    coord = tf.train.Coordinator()
    try:
        threads = []
        for qr in tf.get_collection(tf.GraphKeys.QUEUE_RUNNERS):
          threads.extend(qr.create_threads(sess, coord=coord, daemon=True, start=True))
        print(lbl.eval())
        coord.request_stop()
    except Exception as e:  # pylint: disable=broad-except
        coord.request_stop(e)

[[[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.